#!/usr/bin/env python3
"""Create maze.sdf -- a SMALL sectioned 'maze' world for FAST exploration/inspection testing.

Why: facility_inspection.sdf is 30x20 m and takes many minutes to fully explore. This is a compact
12x8 m box split into 4 rooms (NW/NE/SW/SE) by an internal cross of walls, with a clear central HUB at
the origin connecting all four through doorway gaps -- so it still forces real multi-section navigation
(rooms hidden behind walls) but maps in ~2-4 min. One analog gauge per room (1 seeded anomaly) so the
WHOLE pipeline (explore -> map -> zones -> navigate -> sweep -> segment -> read -> anomaly) works here too.

Self-contained + ADDITIVE: writes a SEPARATE world (maze.sdf), its OWN texture set (maze_tex/) behind its
own no-space symlink (~/.go2_maze_tex), and maze_groundtruth.json. Touches nothing else. Reuses the exact
gz preamble from facility.sdf (physics/sensors/scene/sun/ground) and the draw_gauge dial renderer.

  python3 gen_maze_world.py        # (re-run per machine to refresh textures + the symlink)

Robot HOME (spawn) = (0,0) in the central hub, facing +X. Launch:
  ros2 launch go2_bringup rtabmap_slam.launch.py world:=maze.sdf headless:=false spawn_x:=0 spawn_y:=0 spawn_yaw:=0
"""
import os, sys, json

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_gauges import draw_gauge   # reuse the exact dial renderer (no duplication)

HERE = os.path.dirname(os.path.abspath(__file__))
WORLDS = os.path.abspath(os.path.join(HERE, "..", "worlds"))
DST = os.path.join(WORLDS, "maze.sdf")
TEX_DIR = os.path.join(WORLDS, "maze_tex")
LINK = os.path.expanduser("~/.go2_maze_tex")          # no-space symlink (gz can't resolve the space path)
H, Z, T = 1.6, 0.60, 0.15                             # wall height, gauge centre height, wall thickness
YAW = {"south": 0.0, "north": 0.0, "west": 1.5708, "east": 1.5708}   # panel face normal points INTO room

# Walls: (name, cx, cy, size_x, size_y). 12x8 box (x in [-6,6], y in [-4,4]); internal cross at x=0 / y=0
# each leaving a 2.4 m central doorway gap -> a HUB at the origin connecting all four 6x4 rooms.
WALLS = [
    ("n", 0.0,  4.0, 12.0, T), ("s", 0.0, -4.0, 12.0, T),       # outer N / S
    ("e", 6.0,  0.0, T,  8.0), ("w", -6.0, 0.0, T,  8.0),       # outer E / W
    ("vt", 0.0,  2.6, T, 2.8), ("vb", 0.0, -2.6, T, 2.8),       # internal vertical x=0 (gap y in [-1.2,1.2])
    ("hl", -3.6, 0.0, 4.8, T), ("hr", 3.6, 0.0, 4.8, T),        # internal horizontal y=0 (gap x in [-1.2,1.2])
]

# One gauge per room, on an OUTER wall (>=2.8 m clear floor in front for the approach+strafe), facing in.
LAYOUT = [
    dict(room="NW", asset="NW-PRES-1", wall="west",  x=-5.85, y=2.0,  type="PRESSURE",    unit="bar",
         vmin=0, vmax=16,  reading=9,   danger=0.85, anomaly=False),
    dict(room="NE", asset="NE-VOLT-1", wall="east",  x=5.85,  y=2.0,  type="VOLTAGE",     unit="V",
         vmin=0, vmax=500, reading=470, danger=0.85, anomaly=True),    # over-voltage (seeded fault)
    dict(room="SW", asset="SW-TEMP-1", wall="south", x=-3.0,  y=-3.85, type="TEMPERATURE", unit="degC",
         vmin=0, vmax=150, reading=70,  danger=0.85, anomaly=False),
    dict(room="SE", asset="SE-FLOW-1", wall="south", x=3.0,   y=-3.85, type="FLOW",        unit="L/min",
         vmin=0, vmax=500, reading=240, danger=0.85, anomaly=False),
]

PREAMBLE = '''<?xml version="1.0" ?>
<!-- SMALL sectioned maze for FAST exploration/inspection testing (auto-generated by gen_maze_world.py):
     12x8 m, 4 rooms (NW/NE/SW/SE) around a central HUB. Robot spawns at (0,0) facing +X. -->
<sdf version="1.10">
  <world name="maze">
    <physics name="1ms" type="ignored"><max_step_size>0.002</max_step_size><real_time_factor>1.0</real_time_factor></physics>
    <plugin filename="gz-sim-physics-system"           name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-sensors-system"           name="gz::sim::systems::Sensors"><render_engine>ogre2</render_engine></plugin>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-user-commands-system"     name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-contact-system"           name="gz::sim::systems::Contact"/>
    <plugin filename="gz-sim-imu-system"               name="gz::sim::systems::Imu"/>

    <scene><ambient>0.45 0.45 0.45 1</ambient><background>0.7 0.7 0.8 1</background><grid>false</grid></scene>
    <light type="directional" name="sun"><cast_shadows>true</cast_shadows><pose>0 0 12 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse><specular>0.2 0.2 0.2 1</specular><direction>-0.4 0.3 -0.9</direction></light>

    <model name="ground_plane"><static>true</static><link name="link">
      <collision name="c"><geometry><plane><normal>0 0 1</normal><size>60 60</size></plane></geometry></collision>
      <visual name="v"><geometry><plane><normal>0 0 1</normal><size>60 60</size></plane></geometry>
        <material><ambient>0.8 0.8 0.8 1</ambient><diffuse>0.85 0.85 0.85 1</diffuse></material></visual>
    </link></model>
'''


def wall_xml(name, cx, cy, sx, sy):
    p, sz = f"{cx} {cy} {H/2} 0 0 0", f"{sx} {sy} {H}"
    return (f'        <collision name="{name}_c"><pose>{p}</pose><geometry><box><size>{sz}</size></box></geometry></collision>\n'
            f'        <visual name="{name}_v"><pose>{p}</pose><geometry><box><size>{sz}</size></box></geometry>'
            f'<material><ambient>0.62 0.62 0.68 1</ambient><diffuse>0.62 0.62 0.68 1</diffuse></material></visual>')


def gauge_xml(i, g):
    return (f'    <model name="gauge_{i:02d}"><static>true</static>\n'
            f'      <pose>{g["x"]} {g["y"]} {Z} 0 0 {YAW[g["wall"]]}</pose>\n'
            f'      <link name="link"><visual name="face">\n'
            f'        <geometry><box><size>0.26 0.03 0.26</size></box></geometry>\n'
            f'        <material><ambient>1 1 1 1</ambient><diffuse>1 1 1 1</diffuse><specular>0 0 0 1</specular>\n'
            f'          <pbr><metal>\n'
            f'            <albedo_map>{LINK}/gauge_{i:02d}.png</albedo_map>\n'
            f'            <emissive_map>{LINK}/gauge_{i:02d}.png</emissive_map>\n'
            f'            <metalness>0.0</metalness><roughness>1.0</roughness>\n'
            f'          </metal></pbr>\n'
            f'        </material>\n'
            f'      </visual></link>\n'
            f'    </model>')


def main():
    os.makedirs(TEX_DIR, exist_ok=True)
    gt = []
    for i, g in enumerate(LAYOUT):
        draw_gauge((g["type"], g["unit"], g["vmin"], g["vmax"], g["reading"], g["danger"]),
                   os.path.join(TEX_DIR, f"gauge_{i:02d}.png"))
        gt.append({"id": f"gauge_{i:02d}", "asset": g["asset"], "room": g["room"], "wall": g["wall"],
                   "type": g["type"], "unit": g["unit"], "range_min": g["vmin"], "range_max": g["vmax"],
                   "true_reading": g["reading"], "anomaly": g["anomaly"], "pose": [g["x"], g["y"], Z]})
    json.dump(gt, open(os.path.join(TEX_DIR, "maze_groundtruth.json"), "w"), indent=2)

    if os.path.islink(LINK) or os.path.exists(LINK):
        try:
            os.remove(LINK)
        except OSError:
            pass
    os.symlink(TEX_DIR, LINK)

    walls = "\n".join(wall_xml(*w) for w in WALLS)
    gauges = "\n".join(gauge_xml(i, g) for i, g in enumerate(LAYOUT))
    sdf = (PREAMBLE
           + '\n    <model name="maze"><static>true</static><link name="structure">\n'
           + walls + "\n    </link></model>\n\n"
           + gauges + "\n\n  </world>\n</sdf>\n")
    open(DST, "w").write(sdf)
    print(f"wrote {DST}  (12x8 m, 4 rooms + hub, {len(WALLS)} walls)")
    print(f"  textures via no-space symlink: {LINK} -> {TEX_DIR}")
    print(f"  {len(LAYOUT)} gauges ({sum(g['anomaly'] for g in LAYOUT)} anomaly): "
          + ", ".join(f"{g['room']}:{g['type']}" for g in LAYOUT))


if __name__ == "__main__":
    main()
